# Use an official Python runtime as the base image
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY sort_paragraph.py /app

# Run app.py when the container launches
CMD ["python", "sort_paragraph.py"]